kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certificategenerator-role-minimal
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - get
    - update
    - delete