apiVersion: extensions/v1beta1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ default 1 .Values.replicaCount | int }}
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: certificategenerator-user
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CERT_HOSTNAME
            value: {{ .Values.certhostname }}
          - name: CERT_PASSWORD
            value: {{ .Values.certpassword }}
          - name: CLIENT_CERT_USER
            value: {{ .Values.clientCertificateUser }}
          - name: SAVE_KUBERNETES_SECRET
            value: "true"
          - name: SLEEP_FOREVER
            value: "true"
          - name: SECRET_NAMESPACE
            value: {{ .Release.Namespace }}
        resources:
{{ toYaml .Values.resources | indent 10 }}