apiVersion: batch/v1
kind: Job
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Chart.Name }}
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: certificategenerator-user
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CERT_HOSTNAME
            value: {{ .Values.certhostname }}
          - name: CERT_PASSWORD
            value: {{ .Values.certpassword }}
          - name: CLIENT_CERT_USER
            value: {{ .Values.clientCertificateUser }}
          {{ if .Values.saveCertsAsSecrets }}
          - name: SAVE_KUBERNETES_SECRET
            value: "true"
          {{ end }}
          - name: SECRET_NAMESPACE
            value: {{ .Release.Namespace }}
        resources:
{{ toYaml .Values.resources | indent 10 }}