apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificategenerator-rolebinding-minimal
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certificategenerator-role-minimal
subjects:
- kind: ServiceAccount
  name: certificategenerator-user
  namespace: kube-system